<?php echo $this->render('admin/common/header.phtml'); ?>
	
	<h1 class="page_title icon_folder">Manage ACL Role</h1>
	<hr class="separator">
	
	<div class="column_style1">
		<!-- pager and action -->
		<?php echo $this->pagerAndAction($this->aclroles, 'Add New Role', '/admin/acl-roles/add', $this->auth->isAllowed('admin', 'acl-roles', 'add')); ?>
	
		<table class="itemgrid">
			<tr>
				<th width="25">ID</th>
				<th>Name</th>
				<th width="120">Action</th>
			</tr>
			<?php foreach($this->aclroles as $aclrole): ?>
			<tr>
				<td align="center"><?php echo $aclrole->id; ?></td>
				<td><?php echo $aclrole->name; ?></td>
				<td align="center">
					<a href="<?php echo '/admin/acl-roles/edit/id/'   . $aclrole->id; ?>">edit</a>
					<a href="<?php echo '/admin/acl-roles/delete/id/' . $aclrole->id; ?>" onclick="javascript:return confirm('Are you sure you want to detelete this ACL role?');">delete</a>
				</td>
			</tr>
			<?php endforeach; ?>
		</table>
		
		<?php echo $this->pagerAndAction($this->aclroles, 'Add New Role', '/admin/acl-roles/add', $this->auth->isAllowed('admin', 'acl-roles', 'add')); ?>
	</div>

<?php echo $this->render('admin/common/footer.phtml'); ?>
